<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Paquete;

class PaqueteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Paquete::create([
            'g_email' => 'GamusinoMartinez@gmail.com',
            'g_remitente' => 'Gamusino Martinez',
            'g_telefono' => '968123123',
            'g_nif' => '48712346A',
            'g_bultos' => '3',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Avenida Duque Tamames n45 1D',
            'r_atencion' => 'El Gamu',
            'r_telefono' => '612123123',
            'r_contacto' => 'Gamusino Martinez',
            'r_observaciones' => 'Venid despues de las 18:00',
            'e_pais' => 'España',
            'e_cp' => '30004',
            'e_provincia' => 'Murcia',
            'e_poblacion' => 'Murcia',
            'e_direccion' => 'Avenida Abenarabi ',
            'e_numero' => '33',
            'e_escalera' => '',
            'e_planta' => 'Bajo',
            'e_puerta' => '',
            'e_destinatario' => 'Clinica Bucodental Dr Martinez',
            'e_telefono' => '987654321',
            'e_atencion' => 'Juan',
            'e_observaciones' => 'Entregar antes de las 09:00',
            'tarifa' => '3',
            'terminado' => false,
            'tipo_servicio'=> 'recogida',
            'asignado'=> '3'
        ]);
        Paquete::create([
            'g_email' => 'juanpa@gmail.com',
            'g_remitente' => 'Juan Palomo',
            'g_telefono' => '912345678',
            'g_nif' => '48572345S',
            'g_bultos' => '1',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Calle Naranja',
            'r_atencion' => 'Juan',
            'r_telefono' => '666123123',
            'r_contacto' => 'Juan',
            'r_observaciones' => '',
            'e_pais' => 'España',
            'e_cp' => '3140',
            'e_provincia' => 'Alicante',
            'e_poblacion' => 'Torrevieja',
            'e_direccion' => 'Calle Fragata',
            'e_numero' => '100',
            'e_escalera' => '1',
            'e_planta' => '2',
            'e_puerta' => 'A',
            'e_destinatario' => 'Jesus Fernandez',
            'e_telefono' => '676123456',
            'e_atencion' => 'Jesus',
            'e_observaciones' => 'Nada',
            'tarifa' => '2',
            'terminado' => false,
            'tipo_servicio'=> 'recogida',
            'asignado'=> '3'
        ]);
        Paquete::create([
            'g_email' => 'raulmartinez@gmail.com',
            'g_remitente' => 'Raul Martinez',
            'g_telefono' => '968123123',
            'g_nif' => '48712346A',
            'g_bultos' => '2',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Avenida Ramón n27 3F',
            'r_atencion' => '',
            'r_telefono' => '612123123',
            'r_contacto' => 'Gamusino Martinez',
            'r_observaciones' => 'Venid despues de las 18:00',
            'e_pais' => 'España',
            'e_cp' => '30004',
            'e_provincia' => 'Murcia',
            'e_poblacion' => 'Murcia',
            'e_direccion' => 'Avenida Abenarabi ',
            'e_numero' => '33',
            'e_escalera' => '',
            'e_planta' => 'Bajo',
            'e_puerta' => '',
            'e_destinatario' => 'Clinica Bucodental Dr Martinez',
            'e_telefono' => '987654321',
            'e_atencion' => 'Juan',
            'e_observaciones' => 'Entregar antes de las 09:00',
            'tarifa' => '3',
            'terminado' => false,
            'tipo_servicio'=> 'entrega',
            'asignado'=> '2'
        ]);
        Paquete::create([
            'g_email' => 'sergioramos@gmail.com',
            'g_remitente' => 'Sergio Ramos',
            'g_telefono' => '912555558',
            'g_nif' => '48572345S',
            'g_bultos' => '1',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Calle Limon',
            'r_atencion' => 'Juan',
            'r_telefono' => '666123123',
            'r_contacto' => 'Juan',
            'r_observaciones' => '',
            'e_pais' => 'España',
            'e_cp' => '3140',
            'e_provincia' => 'Alicante',
            'e_poblacion' => 'Torrevieja',
            'e_direccion' => 'Calle Paseo',
            'e_numero' => '86',
            'e_escalera' => '2',
            'e_planta' => '6',
            'e_puerta' => 'g',
            'e_destinatario' => 'Ana Muñoz',
            'e_telefono' => '676123456',
            'e_atencion' => 'Ana',
            'e_observaciones' => 'Nada',
            'tarifa' => '2',
            'terminado' => false,
            'tipo_servicio'=> 'entrega',
            'asignado'=> '2'
        ]);
        Paquete::create([
            'g_email' => 'GamusinoMartinez@gmail.com',
            'g_remitente' => 'Gamusino Martinez',
            'g_telefono' => '968123123',
            'g_nif' => '48712346A',
            'g_bultos' => '3',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Avenida Duque Tamames n45 1D',
            'r_atencion' => 'El Gamu',
            'r_telefono' => '612123123',
            'r_contacto' => 'Gamusino Martinez',
            'r_observaciones' => 'Venid despues de las 18:00',
            'e_pais' => 'España',
            'e_cp' => '30004',
            'e_provincia' => 'Murcia',
            'e_poblacion' => 'Murcia',
            'e_direccion' => 'Avenida Abenarabi ',
            'e_numero' => '33',
            'e_escalera' => '',
            'e_planta' => 'Bajo',
            'e_puerta' => '',
            'e_destinatario' => 'Clinica Bucodental Dr Martinez',
            'e_telefono' => '987654321',
            'e_atencion' => 'Juan',
            'e_observaciones' => 'Entregar antes de las 09:00',
            'tarifa' => '3',
            'terminado' => true,
            'tipo_servicio'=> 'recogida',
            'asignado'=> '3'
        ]);
        Paquete::create([
            'g_email' => 'juanpa@gmail.com',
            'g_remitente' => 'Juan Palomo',
            'g_telefono' => '912345678',
            'g_nif' => '48572345S',
            'g_bultos' => '1',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Calle Naranja',
            'r_atencion' => 'Juan',
            'r_telefono' => '666123123',
            'r_contacto' => 'Juan',
            'r_observaciones' => '',
            'e_pais' => 'España',
            'e_cp' => '3140',
            'e_provincia' => 'Alicante',
            'e_poblacion' => 'Torrevieja',
            'e_direccion' => 'Calle Fragata',
            'e_numero' => '100',
            'e_escalera' => '1',
            'e_planta' => '2',
            'e_puerta' => 'A',
            'e_destinatario' => 'Jesus Fernandez',
            'e_telefono' => '676123456',
            'e_atencion' => 'Jesus',
            'e_observaciones' => 'Nada',
            'tarifa' => '2',
            'terminado' => true,
            'tipo_servicio'=> 'recogida',
            'asignado'=> '3'
        ]);
        Paquete::create([
            'g_email' => 'raulmartinez@gmail.com',
            'g_remitente' => 'Raul Martinez',
            'g_telefono' => '968123123',
            'g_nif' => '48712346A',
            'g_bultos' => '2',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Avenida Ramón n27 3F',
            'r_atencion' => '',
            'r_telefono' => '612123123',
            'r_contacto' => 'Gamusino Martinez',
            'r_observaciones' => 'Venid despues de las 18:00',
            'e_pais' => 'España',
            'e_cp' => '30004',
            'e_provincia' => 'Murcia',
            'e_poblacion' => 'Murcia',
            'e_direccion' => 'Avenida Abenarabi ',
            'e_numero' => '33',
            'e_escalera' => '',
            'e_planta' => 'Bajo',
            'e_puerta' => '',
            'e_destinatario' => 'Clinica Bucodental Dr Martinez',
            'e_telefono' => '987654321',
            'e_atencion' => 'Juan',
            'e_observaciones' => 'Entregar antes de las 09:00',
            'tarifa' => '3',
            'terminado' => true,
            'tipo_servicio'=> 'entrega',
            'asignado'=> '4'
        ]);
        Paquete::create([
            'g_email' => 'sergioramos@gmail.com',
            'g_remitente' => 'Sergio Ramos',
            'g_telefono' => '912555558',
            'g_nif' => '48572345S',
            'g_bultos' => '1',
            'r_pais' => 'España',
            'r_cp' => '03300',
            'r_poblacion' => 'Orihuela',
            'r_direccion' => 'Calle Limon',
            'r_atencion' => 'Juan',
            'r_telefono' => '666123123',
            'r_contacto' => 'Juan',
            'r_observaciones' => '',
            'e_pais' => 'España',
            'e_cp' => '3140',
            'e_provincia' => 'Alicante',
            'e_poblacion' => 'Torrevieja',
            'e_direccion' => 'Calle Paseo',
            'e_numero' => '86',
            'e_escalera' => '2',
            'e_planta' => '6',
            'e_puerta' => 'g',
            'e_destinatario' => 'Ana Muñoz',
            'e_telefono' => '676123456',
            'e_atencion' => 'Ana',
            'e_observaciones' => 'Nada',
            'tarifa' => '2',
            'terminado' => true,
            'tipo_servicio'=> 'entrega',
            'asignado'=> '4'
        ]);
    }
}
